# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_check_card(object):
    def setupUi(self, check_card):
        check_card.setObjectName("check_card")
        check_card.resize(431, 439)
        self.label = QtWidgets.QLabel(check_card)
        self.label.setGeometry(QtCore.QRect(50, 30, 101, 111))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(check_card)
        self.label_2.setGeometry(QtCore.QRect(170, 30, 101, 111))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(check_card)
        self.label_3.setGeometry(QtCore.QRect(290, 30, 101, 111))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(check_card)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 101, 111))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(check_card)
        self.label_5.setGeometry(QtCore.QRect(170, 160, 101, 111))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(check_card)
        self.label_6.setGeometry(QtCore.QRect(290, 160, 101, 111))
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(check_card)
        self.label_8.setGeometry(QtCore.QRect(170, 290, 101, 111))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(check_card)
        self.label_9.setGeometry(QtCore.QRect(290, 290, 101, 111))
        self.label_9.setObjectName("label_9")
        self.label_7 = QtWidgets.QLabel(check_card)
        self.label_7.setGeometry(QtCore.QRect(50, 290, 101, 111))
        self.label_7.setObjectName("label_7")

        self.retranslateUi(check_card)
        QtCore.QMetaObject.connectSlotsByName(check_card)

    def retranslateUi(self, check_card):
        _translate = QtCore.QCoreApplication.translate
        check_card.setWindowTitle(_translate("check_card", "Form"))
        self.label.setText(_translate("check_card", "<html><head/><body><p><br/></p></body></html>"))
        self.label_2.setText(_translate("check_card", "<html><head/><body><p><br/></p></body></html>"))
        self.label_3.setText(_translate("check_card", "<html><head/><body><p><br/></p></body></html>"))
        self.label_4.setText(_translate("check_card", "<html><head/><body><p><br/></p></body></html>"))
        self.label_5.setText(_translate("check_card", "<html><head/><body><p><br/></p></body></html>"))
        self.label_6.setText(_translate("check_card", "<html><head/><body><p><br/></p></body></html>"))
        self.label_8.setText(_translate("check_card", "<html><head/><body><p><br/></p></body></html>"))
        self.label_9.setText(_translate("check_card", "<html><head/><body><p><br/></p></body></html>"))
        self.label_7.setText(_translate("check_card", "<html><head/><body><p><br/></p></body></html>"))
