# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_support_class.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_set_support_class(object):
    def setupUi(self, set_support_class):
        set_support_class.setObjectName("set_support_class")
        set_support_class.resize(262, 150)
        self.comboBox = QtWidgets.QComboBox(set_support_class)
        self.comboBox.setGeometry(QtCore.QRect(65, 60, 121, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(set_support_class)
        self.label.setGeometry(QtCore.QRect(40, 30, 181, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(set_support_class)
        self.pushButton.setGeometry(QtCore.QRect(45, 100, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(set_support_class)
        self.pushButton_2.setGeometry(QtCore.QRect(132, 100, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(set_support_class)
        QtCore.QMetaObject.connectSlotsByName(set_support_class)
        set_support_class.setTabOrder(self.comboBox, self.pushButton)
        set_support_class.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, set_support_class):
        _translate = QtCore.QCoreApplication.translate
        set_support_class.setWindowTitle(_translate("set_support_class", "Form"))
        self.comboBox.setItemText(0, _translate("set_support_class", "all"))
        self.comboBox.setItemText(1, _translate("set_support_class", "saber"))
        self.comboBox.setItemText(2, _translate("set_support_class", "archer"))
        self.comboBox.setItemText(3, _translate("set_support_class", "lancer"))
        self.comboBox.setItemText(4, _translate("set_support_class", "rider"))
        self.comboBox.setItemText(5, _translate("set_support_class", "caster"))
        self.comboBox.setItemText(6, _translate("set_support_class", "assassin"))
        self.comboBox.setItemText(7, _translate("set_support_class", "berseker"))
        self.comboBox.setItemText(8, _translate("set_support_class", "extra"))
        self.label.setText(_translate("set_support_class", "<html><head/><body><p><span style=\" font-size:12pt;\">請先設定支援從者的職階:</span></p><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.pushButton.setText(_translate("set_support_class", "開始截圖"))
        self.pushButton_2.setText(_translate("set_support_class", "取消"))
